"""Added project_id and nanodegree_id as indices on the question table

Revision ID: 8f63db3ad7a1
Revises: cbcb7906e58d
Create Date: 2020-05-21 20:45:11.073358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f63db3ad7a1'
down_revision = 'cbcb7906e58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_question_nanodegree_id'), 'question', ['nanodegree_id'], unique=False)
    op.create_index(op.f('ix_question_project_id'), 'question', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_project_id'), table_name='question')
    op.drop_index(op.f('ix_question_nanodegree_id'), table_name='question')
    # ### end Alembic commands ###
